name: Terraform Test

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  terraform-test:
    name: Test Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Format Terraform Configuration
        run: terraform fmt -check -recursive

  
