name: Terraform Test

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  terraform:
    name: Test Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Format Terraform Configuration
        run: terraform fmt -check -recursive

      - name: Plan Terraform Changes
        run: terraform plan -var-file="terraform.tfvars"

      - name: Apply Terraform Changes
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
